packages:
    alptech/wip: 'dev-master:22153315102a83ad25a6fed4963472e3ed25e5d2'
    maennchen/zipstream-php: 2.1.0
    markbaker/complex: 2.0.0
    markbaker/matrix: 2.0.0
    myclabs/php-enum: 1.7.7
    phpoffice/phpspreadsheet: 1.15.0
    psr/http-client: 1.0.1
    psr/http-factory: 1.0.1
    psr/http-message: 1.0.1
    psr/simple-cache: 1.0.1
    symfony/polyfill-mbstring: v1.20.0
