packages:
    alptech/wip: 'dev-master:22153315102a83ad25a6fed4963472e3ed25e5d2'
    chi-teck/drupal-code-generator: 1.33.0
    composer/semver: 3.2.4
    consolidation/annotated-command: 4.2.3
    consolidation/config: 1.2.1
    consolidation/filter-via-dot-access-data: 1.0.0
    consolidation/log: 2.0.1
    consolidation/output-formatters: 4.1.1
    consolidation/robo: 2.2.1
    consolidation/self-update: 1.2.0
    consolidation/site-alias: 3.0.1
    consolidation/site-process: 4.0.0
    container-interop/container-interop: 1.2.0
    dflydev/dot-access-data: v1.1.0
    dnoegel/php-xdg-base-dir: v0.1.1
    drush/drush: 10.3.6
    grasmash/expander: 1.0.0
    grasmash/yaml-expander: 1.4.0
    guzzlehttp/guzzle: 7.2.0
    guzzlehttp/promises: 1.4.0
    guzzlehttp/psr7: 1.7.0
    league/container: 2.4.1
    maennchen/zipstream-php: 2.1.0
    markbaker/complex: 2.0.0
    markbaker/matrix: 2.0.0
    myclabs/php-enum: 1.7.7
    nikic/php-parser: v4.10.2
    phpoffice/phpspreadsheet: 1.15.0
    psr/container: 1.0.0
    psr/http-client: 1.0.1
    psr/http-factory: 1.0.1
    psr/http-message: 1.0.1
    psr/log: 1.1.3
    psr/simple-cache: 1.0.1
    psy/psysh: v0.10.4
    ralouphie/getallheaders: 3.0.3
    symfony/console: v4.4.17
    symfony/event-dispatcher: v4.4.17
    symfony/event-dispatcher-contracts: v1.1.9
    symfony/filesystem: v4.4.17
    symfony/finder: v5.1.9
    symfony/polyfill-ctype: v1.20.0
    symfony/polyfill-mbstring: v1.20.0
    symfony/polyfill-php73: v1.20.0
    symfony/polyfill-php80: v1.20.0
    symfony/process: v4.4.17
    symfony/service-contracts: v2.2.0
    symfony/var-dumper: v5.1.9
    symfony/yaml: v4.4.17
    twig/twig: v2.14.1
    webflo/drupal-finder: 1.2.2
    webmozart/assert: 1.9.1
    webmozart/path-util: 2.3.0
